ALTER TABLE "CreditDebitNote" ADD COLUMN IF NOT EXISTS "igtfUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CreditDebitNote" ADD COLUMN IF NOT EXISTS "igtfBs" DOUBLE PRECISION NOT NULL DEFAULT 0;
