-- AlterEnum
ALTER TYPE "PermissionKey" ADD VALUE 'RETURN_INVOICE';
ALTER TYPE "PermissionKey" ADD VALUE 'CREDIT_NOTE_SALE';
ALTER TYPE "PermissionKey" ADD VALUE 'DEBIT_NOTE_SALE';
ALTER TYPE "PermissionKey" ADD VALUE 'RETURN_PURCHASE';
ALTER TYPE "PermissionKey" ADD VALUE 'CREDIT_NOTE_PURCHASE';
ALTER TYPE "PermissionKey" ADD VALUE 'DEBIT_NOTE_PURCHASE';
