-- AlterTable
ALTER TABLE "CompanyConfig" ADD COLUMN     "igtfPct" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN     "isIGTFContributor" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "igtfBs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "igtfUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ivaBs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "subtotalBs" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "InvoiceItem" ADD COLUMN     "ivaAmountBs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalBs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "unitPriceBs" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Payment" ADD COLUMN     "igtfBs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "igtfUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;

